### ISSUE TITLE
ParseFloatError when reading a Numeric value due to nul byte padding

### ISSUE THREAD

**Issue by GtrMo** [tmontaigu/dbase-rs#16]
When I tried to read the dbf file provided by the [french land registry](https://cadastre.data.gouv.fr/datasets/cadastre-etalab), I encountered a ParseFloatError on a Numeric field. 
Any 'parcelles' shapefile available should reproduce this error.

I was able to narrow it down to the fact that when a Numeric field is a string padded with NUL bytes, the `value.trim()` call in [`field.rs:286`](https://github.com/tmontaigu/dbase-rs/blob/3e880caf265eeb91d86a66996c7fda4538988f38/src/record/field.rs#L286) does not work ([see playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=25205cb2fb99d11962bac42733b5caf3)).

This behavior is [normal for Rust](https://users.rust-lang.org/t/should-string-from-utf8-remove-trailing-null/52680), but results in a ParseFloatError in `dbase-rs`.

Other dbf libraries do not seem to have this issue. This bug can be resolved by replacing the nul bytes by spaces, as [pyshp](https://github.com/GeospatialPython/pyshp/blob/6229210ade04578d01481d4e947124615a2e2de1/shapefile.py#L1230) does.

Should I open a PR ? If so, do you prefer to modify the `read_string_of_len` function, or should I create another one to read numeric strings ?

Note: this bug is likely to also happen with the `Float` field type, but I haven't tested it.

**Comment by tmontaigu** [comment]
I think the best is to modify the `read_string_of_len` to trim null bytes out of the vec or replace null bytes with spaces as you suggested
