### ISSUE TITLE
Question about working with DateTime and Time types

### ISSUE THREAD

**Issue by worace** [tmontaigu/dbase-rs#24]
Apologies if I'm missing something but it looks like the internal fields for the DateTime and Time types are private and aren't exposed through any getter functions: https://docs.rs/dbase/0.2.1/dbase/struct.DateTime.html

Is there another recommended way to access the data out of these types? Maybe there is a converter trait or something I missed?

I see in Date for example there are methods for getting the year/month/day components: https://docs.rs/dbase/0.2.1/dbase/struct.Date.html#method.year

**Comment by tmontaigu** [comment]
Woops it seems that the accessors/getter functions are indeed missing 😅

**Comment by worace** [comment]
Awesome, thanks!
