### ISSUE TITLE
Generated dbf-file not readable

### ISSUE THREAD

**Issue by michelk** [tmontaigu/dbase-rs#26]
I wrote a function to export a triangular mesh to a shapefile. 

All files are written (shp, shx, dbf) and the shp-file could be opened with QGIS. 

This works, but the dbf-file couldn't be opened: 

```bash
dbfdump msh.dbf 
DBFOpen(msh.dbf,"r") failed.
```

Any idea what the problem could be?

EDIT:  There is a full example, see below.

Thanks.

**Comment by tmontaigu** [comment]
Transfered because its a `dbase` issue.

I've had a deeper look at this, and the problem that we did not count the `deletion flag` field size in the total record size written in the header.

Issue #18 described the same problem

**Comment by michelk** [comment]
Thanks, now it works :)
