### ISSUE TITLE
dbase::Error doesn't implement std::error::Error

### ISSUE THREAD

**Issue by raimundomartins** [tmontaigu/dbase-rs#32]
~~This makes it very annoying to use with other code, I constantly have to do `map_err(|e| ...)`.~~

~~A related issue is with the signature of `ReadableRecord::read_using`: it requires you to return a `Result<Self, FieldIOError>` and `FieldIoError` is not public, making it impossible to do on-the-fly fallable operations without resorting to `panic!()`~~

~~Any chance to make these more compatible with std?~~

Apparently these are fixed in master, so I guess I'm only asking for a new version publish on crates.io. Sorry about that :)

**Comment by tmontaigu** [comment]
0.2.3 is published on crates.io
