### ISSUE TITLE
FieldType is used in a public api but is in a private module 

### ISSUE THREAD

**Issue by apps4uco** [tmontaigu/dbase-rs#33]
FieldType is use in a public api but it is not currently exported.

```
 let ft:FieldType=field.field_type();
```
Error: cannot find type `FieldType` in this scope

Documentation Link: 

pub fn [field_type](https://docs.rs/dbase/0.2.3/dbase/struct.FieldInfo.html#method.field_type)(&self) -> FieldType

There is a non ideal workaround of 
```
let field_type:u8=field.field_type().into();
```
However it would be a fairly simple fix to make the relevant module public or move the enum into a public module,

**Comment by tmontaigu** [comment]
Indeed this is missing 😳, i'll add it
