### ISSUE TITLE
remove chrono dependency?

### ISSUE THREAD

**Issue by Roguelazer** [tmontaigu/dbase-rs#34]
Chrono is caught up in the "reading env vars from C code is unsafe" mess and thus anything that uses dbase-rs will have issues from cargo-audit. What do you think about directly replacing it with `time v0.3`?

**Comment by tmontaigu** [comment]
> Chrono is caught up in the "reading env vars from C code is unsafe" mess

Do you have links that explain this issue ? Ì'd like to learn about it

**Comment by Roguelazer** [comment]
https://github.com/time-rs/time/issues/293
