### ISSUE TITLE
Are there any plans to make use of indices and relations?

### ISSUE THREAD

**Issue by PhilVince96** [tmontaigu/dbase-rs#41]
I have an existing DBase database including multiple .dbf files with relations and indices(.CDX files). If possible, it would be perfect to read (and maybe deserialize) the records with their relations in them and make use of the indices to instantly look up specific records.

Thanks in advance for your answer! 😊

**Comment by tmontaigu** [comment]
So I've never heard of these .CDX files (this dBase lib was motivated by the shapefile format which does not make use of these CDX).

And the problem is that I t seems to be hard (impossible?) to find any kind of specification for the organization of these CDX files

**Comment by PhilVince96** [comment]
I understand. You are absolutely right, I almost found nothing about the specification as well. I guess it is best to just make your own index with a BTreeMap or something similar, if you need it, but if there is no possibility to get a record by index with O(1), an index is useless anyway. It would only save up the comparison of the searched key with every key, but would still take "index" iterations to get the record. 

Thank you nevertheless. 😊
