### ISSUE TITLE
Trailing whitespaces at the beginning of character records are removed

### ISSUE THREAD

**Issue by theCapypara** [tmontaigu/dbase-rs#56]
At the moment the crate removes trailing whitespaces at the beginning of character fields. This is probably fine in most cases, but sometimes there might be a reason for these trailing whitespaces. While trailing whitespaces at the end of a string are padding, those at the beginning are not.

The dbase spec states for character fields:

Symbol | Data Type | Description
-- | -- | --
C | Character | All OEM code page characters - padded with blanks to the width of the field.

(https://www.dbase.com/Knowledgebase/INT/db7_file_fmt.htm)

**Comment by tmontaigu** [comment]
This means we probalby need to pass down an option in the Reader to chose whether these leading whitespace should be trimmed or not

**Comment by tmontaigu** [comment]
'Fixed' by #59
