### ISSUE TITLE
reading fields lazily

### ISSUE THREAD

**Issue by casperhart** [tmontaigu/dbase-rs#73]
I use the datafusion feature for querying a dbase database, but I would like to improve the speed of queries by having some level of predicate pushdown.

The logic used currently is something like this:

```
let reader = Reader::from_path(path);
let records = reader.iter_records();
for record in records.into_iter().enumerate() {
  for field in fields_i_want {
      match record.get(field) {
        // do stuff
      }
  }
}
```

but this reads the entire record in to a hashmap before `record.get(field)` is called. So if I want only one or two fields from a file that contains 50 fields, it's slower than it needs to be, especially when there are memo fields that I want to skip that are being read from a separate file even though they aren't used.

Is there a way to accomplish this in the current state, i.e. iterating over records but reading only the relevant fields? And if not, can you suggest how this might be implemented?

**Comment by tmontaigu** [comment]
You should try with https://docs.rs/dbase/latest/dbase/struct.File.html

**Comment by casperhart** [comment]
I tried a quick implementation, but it errors when I try to read memo fields. It also doesn't make a big speed difference, presumably because the `Reader` is buffered and the `File` is not.

Is there a way to do it using `reader.iter_records_as()` or similar?

**Comment by tmontaigu** [comment]
> I tried a quick implementation, but it errors when I try to read memo fields. It also doesn't make a big speed difference, presumably because the `Reader` is buffered and the `File` is not.
> 

Could you retry with the branch [buffered-file](https://github.com/tmontaigu/dbase-rs/tree/buffered-file)
it should improve the speed problems (but won't change the memo thing)

> Is there a way to do it using `reader.iter_records_as()` or similar?

No its not possible right now

**Comment by casperhart** [comment]
Interestingly when I try on the branch buffered-file it ends up slower. For a query on a file with 500k records + joining a smaller table, it runs in 28s vs. 20s for the standard file or reader.

Also when using the buffered or non-buffered file, I get an off-by-one issue where each subsequent field is shifted to the left.

E.g. I get this:
```
+----------------+-----------------+--------------------------------------+
| isbn           | catalog         | title                                |
+----------------+-----------------+--------------------------------------+
| 021075100426   |                 | JANES ADDICTION                      |
| 325583035043 5 | 046759602     I | F I SHOULD FALL FROM GRACE WITH GOD  |
| 2527303246     | BL              | ACK SABBATH (2010 REMASTERED) (DIGI) |
| 211835626  Z48 | 990         TRI | NITY SESSION                         |
| 58695424       | DANZ            | IG 2 - LUCIFUGE                      |
| 2472521  GEFD2 | 4725      HELL  | FREEZES OVER                         |
| 864626         | BREATH          | LESS                                 |
| 99725  069905  | THROWIN         | G COPPER                             |
| 3928  74321191 | 392    PARIS    | MCLAREN                              |
| 026            | INFAMOUS        | MOBB DEEP                            |
+----------------+-----------------+--------------------------------------+
```
Instead of this:
```
+---------------+-------------+----------------------------------------+
| isbn          | catalog     | title                                  |
+---------------+-------------+----------------------------------------+
| 021075100426  |             | JANES ADDICTION                        |
| 9325583035043 | 5046759602  | IF I SHOULD FALL FROM GRACE WITH GOD   |
| 602527303246  |             | BLACK SABBATH (2010 REMASTERED) (DIGI) |
| 743211835626  | Z48990      | TRINITY SESSION                        |
| 731458695424  |             | DANZIG 2 - LUCIFUGE                    |
| 720642472521  | GEFD24725   | HELL FREEZES OVER                      |
| 078221864626  |             | BREATHLESS                             |
| 008811099725  | 069905      | THROWING COPPER                        |
| 743211913928  | 74321191392 | PARIS                                  |
| 078636648026  |             | INFAMOUS                               |
+---------------+-------------+----------------------------------------+
```

**Comment by casperhart** [comment]
I have two branches in my fork for the datafusion update: they are `buffered-file` and `non-buffered-file` if you'd like to take a look

**Comment by tmontaigu** [comment]
I've made some changes locally that makes reading using dbase::File as Fast as dbase::Reader, and it seems to be faster when only reading a subset of the fields.

Are you able to share the 500k record file ?
And what command should I run to test datafusion ?

**Comment by casperhart** [comment]
If you're able to push those changes I can test again, but I'm not sure if I can share the file due to the data contained.

For testing datafusion, the code I'm running is very similar to the datafusion example in this crate

**Comment by tmontaigu** [comment]
Well, in that case I'll just push my work in progress to a new branch so you could try it with your file

It should be faster

**Comment by tmontaigu** [comment]
I have pushed the work in progress to this branch https://github.com/tmontaigu/dbase-rs/tree/faster-file

I don't have any dbf with memo file to test, but the idea is that dbase::File won't read the memo fields unless explicitely asked for. It also improves reading non memo fields for dbase::File, and so if you don't read all the fields in the file, it will be faster

**Comment by casperhart** [comment]
Nice, 4x faster on the query I'm looking at, 5s vs 20s. Even when reading a memo field, it was 6s vs 20s.

I'll open a separate issue for the off by one error I see with this, for testing I've been putting in a temporary fix, but it breaks the tests.

**Comment by tmontaigu** [comment]
Ok that's better

By doing that I found that, if your file has a lot of deleted records then ,I think the dbase::Reader becomes slower that what it could be due to how it skips them, I will also try to push a fix that should improve that case

**Comment by casperhart** [comment]
Do you know when you'll have a PR ready for the faster file implementation? I have a version on my local I can use for the time being but would be good to see it upstream

**Comment by tmontaigu** [comment]
Yes i plan on doing a first PR/merge this week and maybe then a few iterations If I find new things
