### ISSUE TITLE
Problem with reading dbf file in CP1251

### ISSUE THREAD

**Issue by shh07** [tmontaigu/dbase-rs#83]
I'm getting error <the trait bound `yore::code_pages::CP1251: Encoding` is not satisfied> while compiling the project with dbase v.0.4.0 and yore v.1.0.1

> use dbase::FieldValue;
use yore::code_pages::{CP1251, CP850};
fn main() {
    let mut reader = dbase::Reader::from_path_with_encoding("D:\projects\dbf_test\data.dbf", CP1251).expect("err");
}

**Comment by tmontaigu** [comment]
Did you enable the `yore` feature of dbase ? --features=yore
